vim.api.nvim_create_autocmd("LspAttach", {
	callback = function(e)
		-- Set up keybindings
		vim.keymap.set({ "n", "v" }, "<leader>e", function()
			vim.lsp.buf.hover()
		end, { buffer = e.buf, desc = "(vim.lsp.buf.hover) Show hover information" })
		vim.keymap.set({ "n", "v" }, "<leader>rn", function()
			vim.lsp.buf.rename()
		end, { buffer = e.buf, desc = "(vim.lsp.buf.rename) Rename symbol under cursor" })
		vim.keymap.set({ "n", "v" }, "<leader>gd", function()
			vim.lsp.buf.definition()
		end, { buffer = e.buf, desc = "(vim.lsp.buf.definition) Go to definition" })
		vim.keymap.set({ "n", "v" }, "<leader>gt", function()
			vim.lsp.buf.type_definition()
		end, { buffer = e.buf, desc = "(vim.lsp.buf.type_definition) Go to type definition" })
		vim.keymap.set({ "n", "v" }, "<leader>gr", function()
			vim.lsp.buf.references()
		end, { buffer = e.buf, desc = "(vim.lsp.buf.references) Show references" })
		vim.keymap.set({ "n", "v" }, "<leader>gi", function()
			vim.lsp.buf.implementation()
		end, { buffer = e.buf, desc = "(vim.lsp.buf.implementation) Go to implementation" })
		vim.keymap.set({ "n", "v" }, "<leader>ca", function()
			vim.lsp.buf.code_action()
		end, { buffer = e.buf, desc = "(vim.lsp.buf.code_action) Show code actions" })
		vim.keymap.set("n", "<leader>bf", function()
			vim.lsp.buf.format()
		end, { buffer = e.buf, desc = "(vim.lsp.buf.format) Format current buffer" })
	end,
})
