require("config.general")
require("config.remaps")
require("config.lazy")
require("config.set")
require("config.search-remaps")
require("config.diagnostics")
require("config.lsp")
require("config.autocmds")
